src/Project01-Team07/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Project01_Team07.Models
{
    public class Student
    {
    
        [ScaffoldColumn(false)]
        public int StudentID { get; set; }
        [Required]
        public string email { get; set; }
        [Display(Name = "FirstName")]
        public string firstName { get; set; }
        [Display(Name = "LastName")]
        public string lastName { get; set; }
        public bool isEnrolled { get; set; }
      
        public Student()
        {
            isEnrolled = false;
        }



    }
}







src/Project01-Team07/Controllers/EnrollmentsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Project01_Team07.Models;
using System.Security.Claims;
using System;

namespace Project01_Team07.Controllers
{
    public class EnrollmentsController : Controller
    {
        private ApplicationDbContext _context;

        public EnrollmentsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Enrollments
        public IActionResult Index()
        {
            return View(_context.Enrollments.ToList());
        }

        // GET: Enrollments/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Enrollment enrollment = _context.Enrollments.Single(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        public IActionResult Create()
        {
            var sections = _context.Section.Where(m => m.isAssigned == true).ToList();
            var s = _context.Students.Single(m => m.email == User.GetUserName());
            ViewBag.Sections = new MultiSelectList(sections, "sectionCRN", "sectionName");
            ViewData["StudentID"] = s.StudentID;
            return View();
        }

        // POST: Enrollments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Enrollment enrollment)
        {
            var c = HttpContext.Request;
            if (ModelState.IsValid)
            {
                int count = 0;
                var crns = c.Form["sectionCRN"];
                foreach (string crn in crns)
                {
                    count++;
                    if (count == 1)
                    {
                        enrollment.crn1 = Int32.Parse(crn);
                    }
                    else if (count == 2)
                    {
                        enrollment.crn2 = Int32.Parse(crn);
                    }
                    else
                    {
                        enrollment.crn3 = Int32.Parse(crn);
                    }
                }
                _context.Enrollments.Add(enrollment);
                _context.SaveChanges();
                var s = _context.Students.Single(m => m.email == User.GetUserName());
                s.isEnrolled = true;
                _context.Update(s);
                _context.SaveChanges();
                return RedirectToAction("Index","Students");
            }
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Enrollment enrollment = _context.Enrollments.Single(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Update(enrollment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Enrollment enrollment = _context.Enrollments.Single(m => m.EnrollmentID == id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = _context.Enrollments.Single(m => m.EnrollmentID == id);
            _context.Enrollments.Remove(enrollment);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Project01-Team07/Controllers/StudentsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Project01_Team07.Models;
using System.Security.Claims;
using System;

namespace Project01_Team07.Controllers
{
    public class StudentsController : Controller
    {
        private ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Students
        public IActionResult Index()
        {
            var student = _context.Students.Single(m => m.email == User.GetUserName());
            if (student.isEnrolled)
            {
                var crnss = _context.Section.Where(m => m.isAssigned == true).ToList();
                var enrollment = _context.Enrollments.Single(m => m.StudentID == student.StudentID);
                ViewData["crn1"] = enrollment.crn1;
                ViewData["crn2"] = enrollment.crn2;
                ViewData["crn3"] = enrollment.crn3;
            }
            return View(student);
        }

        // POST: Students/Feedback
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Feedback()
        {
            var c = HttpContext.Request;
            System.Diagnostics.Debug.WriteLine("==========================");
            System.Diagnostics.Debug.WriteLine(c.Form["crn"].ToString());
            System.Diagnostics.Debug.WriteLine(c.Form["feedbackType"].ToString());
            string crn = c.Form["crn"].ToString();
            ViewData["section"]= c.Form["crn"].ToString();
            if (c.Form["feedbackType"].ToString().Equals("daily"))
            {
                return RedirectToAction("Daily", "Feedbacks",new { crn = ViewData["section"] });
            }else if (c.Form["feedbackType"].ToString().Equals("monthly"))
            {
                return RedirectToAction("Month", "Feedbacks", new { crn = ViewData["section"] });
            }
            else if (c.Form["feedbackType"].ToString().Equals("semister"))
            {
                return RedirectToAction("Semister", "Feedbacks", new { crn = ViewData["section"] });
            }
            else
            {
                return View();
            }
            
        }

        // GET: Students/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Student student = _context.Students.Single(m => m.StudentID == id);
            if (student == null)
            {
                return HttpNotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Students.Add(student);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Student student = _context.Students.Single(m => m.StudentID == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Update(student);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Student student = _context.Students.Single(m => m.StudentID == id);
            if (student == null)
            {
                return HttpNotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Student student = _context.Students.Single(m => m.StudentID == id);
            _context.Students.Remove(student);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Project01-Team07/Views/Students/Create.cshtml
@model Project01_Team07.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="firstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="isEnrolled" />
                    <label asp-for="isEnrolled"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="lastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Project01-Team07/Views/Students/Delete.cshtml
@model Project01_Team07.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.isEnrolled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.isEnrolled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/Project01-Team07/Views/Students/Details.cshtml
@model Project01_Team07.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>


    <h4>Student</h4>
    <hr />
  
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.firstName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.firstName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.lastName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.lastName)
            </dd>
        </dl>
@if (model.isEnrolled)
{


}
else
{
    <a asp-controller="Enrollments" asp-action="Create" class="form-horizontal">enroll</a>
}
       


  
       

src/Project01-Team07/Views/Students/Edit.cshtml
@model Project01_Team07.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="firstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="isEnrolled" />
                    <label asp-for="isEnrolled"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="lastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Project01-Team07/Views/Students/Index.cshtml
@model Project01_Team07.Models.Student

@{
    ViewData["Title"] = "Student - Home";
}

<!-- Page Header -->
<div class="content bg-image overflow-hidden" style="background-image: url('/assets/img/photos/photo3@2x.jpg');">
    <div class="push-50-t push-15">
        <h1 class="h2 text-white animated zoomIn">Dashboard</h1>
        <h2 class="h5 text-white-op animated zoomIn">Welcome @Model.firstName @Model.lastName</h2>
    </div>
</div>
<!-- END Page Header -->
@if (Model.isEnrolled)
{
    <div class="content content-narrow">
        <!-- Material Design -->
        @*<h2 class="content-heading">Material Design</h2>*@
        <div class="row bg-white">
                <!-- Static Labels -->
                <div class="block">
                    <div class="block-header bg-gray-lighter">
                        <h3 class="block-title">Feedback Generation</h3>
                    </div>
                    <div class="block-content">
                        <form class="form-horizontal push-10-t" asp-controller="Students" asp-action="Feedback" method="post" >
                            <div class="col-sm-4">
                                <div class="form-group">
                                        <div class="form-material floating">
                                            <select class="form-control" id="crn" name="crn" size="1">
                                                <option></option>
                                                <option value="@ViewData["crn1"]">@ViewData["crn1"]</option>
                                                <option value="@ViewData["crn2"]">@ViewData["crn2"]</option>
                                                <option value="@ViewData["crn3"]">@ViewData["crn3"]</option>
                                            </select>
                                            <label for="crn">Please Select CRN</label>
                                        </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                        <div class="form-material floating">
                                            <select class="form-control" id="feedbackType" name="feedbackType" size="1">
                                                <option></option>
                                                <option value="daily">Daily</option>
                                                <option value="monthly">Monthly</option>
                                                <option value="semister">Semister</option>
                                            </select>
                                            <label for="feedbackType">Please Select Feedback type</label>
                                        </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="col-sm-9">
                                        <button class="btn btn-sm btn-primary" type="submit">Generate</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- END Static Labels -->
            </div>
        </div>

}
else
{
    <label>As you are first time user, Please enroll to the courses you registered: </label>
    <a asp-controller="Enrollments" asp-action="Create" class="form-horizontal">Enroll</a>
}