src/Project01-Team07/Models/Faculty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Project01_Team07.Models
{
    public class Faculty
    {
        [ScaffoldColumn(false)]
        public int FacultyID { get; set; }
        [Required]
        [Display(Name = "LastName")]
        public string lastName { get; set; }
        [Display(Name = "FirstName")]
        public string firstName { get; set; }
       
      
        [Required]
        public string email { get; set; }
        public string departmentname { get; set; }
        public bool isFacultyEnrolled { get; set; }

        public Faculty()
        {
            isFacultyEnrolled = false;
        }

        public virtual ApplicationUser ApplicationUser { get; set; }

       
    }
}


src/Project01-Team07/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Project01_Team07.Models
{
    public class Feedback
    {
        [ScaffoldColumn(false)]
        public int FeedbackID { get; set; }
        [Required]
        public string FeedbackResponse { get; set; }

        public string FeedbackComment { get; set; }

        public string type { get; set; }

        public string crn { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime CreatedUtc { get; set; }

    }
}

src/Project01-Team07/Controllers/FacultiesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Project01_Team07.Models;
using System.Security.Claims;

namespace Project01_Team07.Controllers
{
    public class FacultiesController : Controller
    {
        private ApplicationDbContext _context;

        public FacultiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Faculties
        public IActionResult Index()
        {

            var faculty = _context.Faculties.Single(m => m.email == User.GetUserName());
            if (faculty.isFacultyEnrolled)
            {

                var enrollment = _context.Facultyenrollment.Single(m => m.FacultyID == faculty.FacultyID);
                ViewData["crn1"] = enrollment.crn1;
                ViewData["crn2"] = enrollment.crn2;
                ViewData["crn3"] = enrollment.crn3;
            }
            return View(faculty);
        }

        //// POST: Faculties
        //public IActionResult Index()
        //{
        //    return View("Feedback");
        //}

        public IActionResult Feedback()
        {
            return View();
        }

        // GET: Faculties/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculties.Single(m => m.FacultyID == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Faculties.Add(faculty);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculties.Single(m => m.FacultyID == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Update(faculty);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculties.Single(m => m.FacultyID == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Faculty faculty = _context.Faculties.Single(m => m.FacultyID == id);
            _context.Faculties.Remove(faculty);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Project01-Team07/Controllers/FacultyenrollmentsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Project01_Team07.Models;
using System.Security.Claims;
using System;

namespace Project01_Team07.Controllers
{
    public class FacultyenrollmentsController : Controller
    {
        private ApplicationDbContext _context;

        public FacultyenrollmentsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Facultyenrollments
        public IActionResult Index()
        {
            return View(_context.Facultyenrollment.ToList());
        }

        // GET: Facultyenrollments/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Facultyenrollment facultyenrollment = _context.Facultyenrollment.Single(m => m.facEnrollmentID == id);
            if (facultyenrollment == null)
            {
                return HttpNotFound();
            }

            return View(facultyenrollment);
        }

        // GET: Facultyenrollments/Create
        public IActionResult Create()
        {
        var f = _context.Faculties.Single(m => m.email == User.GetUserName());
        var sections = _context.Section.Where(m=>m.isAssigned==false).ToList();
        ViewBag.Sections = new MultiSelectList(sections, "sectionCRN", "sectionName");
        ViewData["FacultyID"] = f.FacultyID;
        return View();
        }

        // POST: Facultyenrollments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Facultyenrollment facultyenrollment)
        {
            var c = HttpContext.Request;
            if (ModelState.IsValid)
            {
                int count = 0;
                var crns = c.Form["sectionCRN"];
                foreach (string crn in crns)
                {
                    count++;
                    if(count == 1)
                    {
                        facultyenrollment.crn1 = Int32.Parse(crn);
                    }else if (count ==2)
                    {
                        facultyenrollment.crn2 = Int32.Parse(crn);
                    }else
                    {
                        facultyenrollment.crn3 = Int32.Parse(crn);
                    }
                }
                

                _context.Facultyenrollment.Add(facultyenrollment);
                _context.SaveChanges();
                var crn1 = _context.Section.Single(m => m.sectionCRN == facultyenrollment.crn1.ToString());
                crn1.isAssigned = true;
                _context.Update(crn1);
                _context.SaveChanges();
                var crn2 = _context.Section.Single(m => m.sectionCRN == facultyenrollment.crn2.ToString());
                crn2.isAssigned = true;
                _context.Update(crn2);
                _context.SaveChanges();
                var crn3 = _context.Section.Single(m => m.sectionCRN == facultyenrollment.crn3.ToString());
                crn3.isAssigned = true;
                _context.Update(crn3);
                _context.SaveChanges();

                var s = _context.Faculties.Single(m => m.email == User.GetUserName());
                s.isFacultyEnrolled = true;
                _context.Update(s);
                _context.SaveChanges();

            return RedirectToAction("Index","Faculties");
            }
            return View(facultyenrollment);
        }

        // GET: Facultyenrollments/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Facultyenrollment facultyenrollment = _context.Facultyenrollment.Single(m => m.facEnrollmentID == id);
            if (facultyenrollment == null)
            {
                return HttpNotFound();
            }
            return View(facultyenrollment);
        }

        // POST: Facultyenrollments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Facultyenrollment facultyenrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Update(facultyenrollment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(facultyenrollment);
        }

        // GET: Facultyenrollments/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Facultyenrollment facultyenrollment = _context.Facultyenrollment.Single(m => m.facEnrollmentID == id);
            if (facultyenrollment == null)
            {
                return HttpNotFound();
            }

            return View(facultyenrollment);
        }

        // POST: Facultyenrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Facultyenrollment facultyenrollment = _context.Facultyenrollment.Single(m => m.facEnrollmentID == id);
            _context.Facultyenrollment.Remove(facultyenrollment);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Project01-Team07/Views/Faculties/Feedback.cshtml
<div style="margin-top:5px;">
    <div class="col-lg-6">
        <!-- Icon Based -->
        <div class="block block-themed">
            <div class="block-header bg-primary">
                <ul class="block-options">
                    <li>
                        <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                    </li>
                    <li>
                        <button type="button" data-toggle="block-option" data-action="refresh_toggle" data-action-mode="demo"><i class="si si-refresh"></i></button>
                    </li>
                    <li>
                        <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                    </li>
                </ul>
                <h3 class="block-title">Questions And Responses</h3>
            </div>
            <div class="block-content">
                <ul class="list list-timeline pull-t">
                    <!-- Facebook Notification -->
                    <li>
                        @*<div class="list-timeline-time">3 hrs ago</div>*@
                        <i class="fa fa-check-circle list-timeline-icon bg-default"></i>
                        <div class="list-timeline-content">
                            <p class="font-s15">The Instructor requried that students use course concepts to demonstrate understanding</p>
                            <p class="font-w600">Strongly Agree</p>
                        </div>
                    </li>
                    <!-- END Facebook Notification -->
                    <!-- Facebook Notification -->
                    <li>
                        @*<div class="list-timeline-time">3 hrs ago</div>*@
                        <i class="fa fa-check-circle list-timeline-icon bg-default"></i>
                        <div class="list-timeline-content">
                            <p class="font-s15">The Instructor treated students fairly</p>
                            <p class="font-w600">Strongly Agree</p>
                        </div>
                    </li>
                    <!-- END Facebook Notification -->
                    <!-- Facebook Notification -->
                    <li>
                        @*<div class="list-timeline-time">3 hrs ago</div>*@
                        <i class="fa fa-check-circle list-timeline-icon bg-default"></i>
                        <div class="list-timeline-content">
                            <p class="font-s15">The Instructor teaching methods were effective</p>
                            <p class="font-w600">Strongly Agree</p>
                        </div>
                    </li>
                    <!-- END Facebook Notification -->
                </ul>
            </div>
        </div>
        <!-- END Icon Based -->
    </div>
    <div class="col-lg-6">
        <!-- Icon Based -->
        <div class="block block-themed">
            <div class="block-header bg-primary">
                <ul class="block-options">
                    <li>
                        <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                    </li>
                    <li>
                        <button type="button" data-toggle="block-option" data-action="refresh_toggle" data-action-mode="demo"><i class="si si-refresh"></i></button>
                    </li>
                    <li>
                        <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                    </li>
                </ul>
                <h3 class="block-title">Comments</h3>
            </div>
            <div class="block-content">
                <ul class="list list-timeline pull-t">
                    <!-- Facebook Notification -->
                    <li>
                        @*<div class="list-timeline-time">3 hrs ago</div>*@
                        <i class="fa fa-comment list-timeline-icon bg-default"></i>
                        <div class="list-timeline-content">
                            <p class="font-w600">@*+ 290 Page Likes*@</p>
                            <p class="font-s13">Excited! course is coming to end. This course helped to develop in many aspects .
                            Angular2 is Intresting </p>
                        </div>
                    </li>
                    <!-- END Facebook Notification -->
                    <!-- Facebook Notification -->
                    <li>
                        @*<div class="list-timeline-time">3 hrs ago</div>*@
                        <i class="fa fa-comment list-timeline-icon bg-default"></i>
                        <div class="list-timeline-content">
                            <p class="font-w600">@*+ 290 Page Likes*@</p>
                            <p class="font-s13">Classes are effective and new topics are demostarted well.</p>
                        </div>
                    </li>
                    <!-- END Facebook Notification -->
                    <!-- Facebook Notification -->
                    <li>
                        @*<div class="list-timeline-time">3 hrs ago</div>*@
                        <i class="fa fa-comment list-timeline-icon bg-default"></i>
                        <div class="list-timeline-content">
                            <p class="font-w600">@*+ 290 Page Likes*@</p>
                            <p class="font-s13">This course is useful considering career. Well structered, trending technologies. working for real-time project is a learning which will help me in future.</p>
                        </div>
                    </li>
                    <!-- END Facebook Notification -->
                </ul>
            </div>
        </div>
        <!-- END Icon Based -->
    </div>
</div>

src/Project01-Team07/Views/Faculties/Index.cshtml
@model Project01_Team07.Models.Faculty

@{
    ViewData["Title"] = "Faculties - Home";
}

<!-- Page Header -->
<div class="content bg-image overflow-hidden" style="background-image: url('/assets/img/photos/photo3@2x.jpg');">
    <div class="push-50-t push-15">
        <h1 class="h2 text-white animated zoomIn">Dashboard</h1>
        <h2 class="h5 text-white-op animated zoomIn">Welcome @Model.firstName @Model.lastName</h2>
    </div>
</div>
<!-- END Page Header -->
@if (Model.isFacultyEnrolled)
{
    <div class="content content-narrow">
        <!-- Material Design -->
        @*<h2 class="content-heading">Material Design</h2>*@
        <div class="row bg-white">
                <!-- Static Labels -->
                <div class="block">
                    <div class="block-header bg-gray-lighter">
                        <h3 class="block-title">Feedback Generation</h3>
                    </div>
                    <div class="block-content">
                        <form class="form-horizontal push-10-t" asp-controller="Faculties" asp-action="Feedback" method="post" >
                            <div class="col-sm-4">
                                <div class="form-group">
                                        <div class="form-material floating">
                                            <select class="form-control" id="crn" name="crn" size="1">
                                                <option></option>
                                                <option value="@ViewData["crn1"]">@ViewData["crn1"]</option>
                                                <option value="@ViewData["crn2"]">@ViewData["crn2"]</option>
                                                <option value="@ViewData["crn3"]">@ViewData["crn3"]</option>
                                            </select>
                                            <label for="crn">Please Select CRN</label>
                                        </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                        <div class="form-material floating">
                                            <select class="form-control" id="feedbackType" name="feedbackType" size="1">
                                                <option></option>
                                                <option value="daily">Daily</option>
                                                <option value="monthly">Monthly</option>
                                                <option value="semister">Semister</option>
                                            </select>
                                            <label for="feedbackType">Please Select Feedback type</label>
                                        </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <div class="col-sm-9">
                                        <button class="btn btn-sm btn-primary" type="submit">Generate</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- END Static Labels -->
            </div>
        </div>

}
else
{
    <label>As you are first time user, Please enroll to the courses you registered: </label>
    <a asp-controller="Facultyenrollments" asp-action="Create" class="form-horizontal">Enroll</a>
}