src/Project01-Team07/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Project01_Team07.Models
{
    public class Feedback
    {
        [ScaffoldColumn(false)]
        public int FeedbackID { get; set; }
        [Required]
        public string FeedbackResponse { get; set; }

        public string FeedbackComment { get; set; }

        public string type { get; set; }

        public string crn { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd H:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime CreatedUtc { get; set; }

    }
}

src/Project01-Team07/Controllers/FeedbacksController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Project01_Team07.Models;
using System.Security.Claims;
using System;

namespace Project01_Team07.Controllers
{
    public class FeedbacksController : Controller
    {
        private ApplicationDbContext _context;

        public FeedbacksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Feedbacks
        public IActionResult Index()
        {
            return View(_context.Feedback.ToList());
        }

        // GET: Daily
        public IActionResult Daily(string crn)
        {
            var student = _context.Students.Single(m => m.email == User.GetUserName());
            var fbHistory = _context.FeedbackHistory.SingleOrDefault(m => m.StudentID == student.StudentID.ToString() && m.type == "Daily" && m.CreatedUtc == DateTime.Today && m.crn == crn);
            if (fbHistory == null)
            {
                ViewData["section"] = crn;
                return View();
            }
            else {
                return RedirectToAction("Already");
            }
        }
        // POST: Students/Feedback
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DailySave()
        {
            try
            {

                var student = _context.Students.Single(m => m.email == User.GetUserName());
                var c = HttpContext.Request;
                System.Diagnostics.Debug.WriteLine("==========================");
                System.Diagnostics.Debug.WriteLine(c.Form["q1"].ToString());
                System.Diagnostics.Debug.WriteLine(c.Form["comments"].ToString());
                Feedback feedback = new Feedback();
                feedback.FeedbackResponse = c.Form["q1"].ToString() + "," + c.Form["q2"].ToString() + "," + c.Form["q3"].ToString();
                feedback.crn = c.Form["crn"].ToString();
                feedback.FeedbackComment = c.Form["comments"].ToString();
                feedback.CreatedUtc = DateTime.Today;
                feedback.type = "Daily";
                _context.Feedback.Add(feedback);
                _context.SaveChanges();
                FeedbackHistory feedbackHistory = new FeedbackHistory();
                feedbackHistory.StudentID = student.StudentID + "";
                feedbackHistory.type = "Daily";
                feedbackHistory.crn = c.Form["crn"].ToString();
                feedbackHistory.CreatedUtc = DateTime.Today;
                _context.FeedbackHistory.Add(feedbackHistory);
                _context.SaveChanges();
                return RedirectToAction("Success");
            }
            catch (System.Exception e)
            {
                return RedirectToAction("Failure");
            }

        }



        // GET: Month
        public IActionResult Month(string crn)
        {
            var student = _context.Students.Single(m => m.email == User.GetUserName());
            var fbHistory = _context.FeedbackHistory.SingleOrDefault(m => m.StudentID == student.StudentID.ToString() && m.type == "Month" && m.CreatedUtc == DateTime.Today && m.crn == crn);
            if (fbHistory == null)
            {
                ViewData["section"] = crn;
                return View();
            }
            else {
                return RedirectToAction("Already");
            }
        }
        // POST: Students/Feedback
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MonthSave()
        {
            try
            {
                var student = _context.Students.Single(m => m.email == User.GetUserName());
                var c = HttpContext.Request;
                System.Diagnostics.Debug.WriteLine("==========================");
                System.Diagnostics.Debug.WriteLine(c.Form["q1"].ToString());
                System.Diagnostics.Debug.WriteLine(c.Form["comments"].ToString());
                Feedback feedback = new Feedback();
                feedback.FeedbackResponse = c.Form["q1"].ToString() + "," + c.Form["q2"].ToString() + "," + c.Form["q3"].ToString();
                feedback.crn = c.Form["crn"].ToString();
                feedback.FeedbackComment = c.Form["comments"].ToString();
                feedback.CreatedUtc = DateTime.Today;
                feedback.type = "Month";
                _context.Feedback.Add(feedback);
                _context.SaveChanges();


                FeedbackHistory feedbackHistory = new FeedbackHistory();
                feedbackHistory.StudentID = student.StudentID + "";
                feedbackHistory.type = "Month";
                feedbackHistory.crn = c.Form["crn"].ToString();
                feedbackHistory.CreatedUtc = DateTime.Today;
                _context.FeedbackHistory.Add(feedbackHistory);
                _context.SaveChanges();

                return RedirectToAction("Success");
            }
            catch (System.Exception e)
            {
                return RedirectToAction("Failure");
            }
        }

        // GET: Semister
        public IActionResult Semister(string crn)
        {
            var student = _context.Students.Single(m => m.email == User.GetUserName());
            var fbHistory = _context.FeedbackHistory.SingleOrDefault(m => m.StudentID == student.StudentID.ToString() && m.type == "Semister" && m.CreatedUtc == DateTime.Today && m.crn == crn);
            if (fbHistory == null)
            {
                ViewData["section"] = crn;
                return View();
            }
            else {
                return RedirectToAction("Already");
            }
        }
        // POST: Students/Feedback
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SemisterSave()
        {
            try
            {
                var c = HttpContext.Request;
                System.Diagnostics.Debug.WriteLine("==========================");
                System.Diagnostics.Debug.WriteLine(c.Form["q1"].ToString());
                System.Diagnostics.Debug.WriteLine(c.Form["comments"].ToString());
                Feedback feedback = new Feedback();
                feedback.FeedbackResponse = c.Form["q1"].ToString() + "," + c.Form["q2"].ToString() + "," + c.Form["q3"].ToString();
                feedback.crn = c.Form["crn"].ToString();
                feedback.FeedbackComment = c.Form["comments"].ToString();
                feedback.CreatedUtc = DateTime.Today;
                feedback.type = "Semister";
                _context.Feedback.Add(feedback);
                _context.SaveChanges();

                var student = _context.Students.Single(m => m.email == User.GetUserName());
                FeedbackHistory feedbackHistory = new FeedbackHistory();
                feedbackHistory.StudentID = student.StudentID + "";
                feedbackHistory.type = "Semister";
                feedbackHistory.crn = c.Form["crn"].ToString();
                feedbackHistory.CreatedUtc = DateTime.Today;
                _context.FeedbackHistory.Add(feedbackHistory);
                _context.SaveChanges();
                return RedirectToAction("Success");
            }
            catch (System.Exception e)
            {
                return RedirectToAction("Failure");
            }
        }

        // GET: Success
        public IActionResult Success()
        {
            return View();
        }

        // GET: Success
        public IActionResult Already()
        {
            return View();
        }

        // GET: Failure
        public IActionResult Failure()
        {
            return View();
        }

        // GET: Feedbacks/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Feedback feedback = _context.Feedback.Single(m => m.FeedbackID == id);
            if (feedback == null)
            {
                return HttpNotFound();
            }

            return View(feedback);
        }

        // GET: Feedbacks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Feedbacks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _context.Feedback.Add(feedback);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feedback);
        }

        // GET: Feedbacks/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Feedback feedback = _context.Feedback.Single(m => m.FeedbackID == id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _context.Update(feedback);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Feedback feedback = _context.Feedback.Single(m => m.FeedbackID == id);
            if (feedback == null)
            {
                return HttpNotFound();
            }

            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]

src/Project01-Team07/Views/Feedbacks/Already.cshtml
@{
    ViewData["Title"] = "Feedback Success";
}
<!-- Page Header -->
<div class="content bg-image overflow-hidden" style="background-image: url('/assets/img/photos/photo3@2x.jpg');">
    <div class="push-50-t push-15">
        <h1 class="h2 text-white animated zoomIn">Thank you</h1>
        <h2 class="h5 text-white-op animated zoomIn">Feedack already submitted</h2>
    </div>
</div>
<!-- END Page Header -->

src/Project01-Team07/Views/Feedbacks/Daily.cshtml
@{
    ViewData["Title"] = "Daily - Feedback";
}

<h2>Daily - Feedback</h2>

<div class="content content-narrow">
    <!-- Material Design -->
    @*<h2 class="content-heading">Material Design</h2>*@
    <div class="row bg-white">
        <!-- Static Labels -->
        <div class="block">
            <div class="block-header bg-gray-lighter">
                <h3 class="block-title">Daily Feedback form <form action="/" method="post"></form></h3>
            </div>
            <div class="block-content">
                <form class="form-horizontal push-10-t" asp-controller="Feedbacks" asp-action="DailySave" method="post">
                    <input type="text" name="crn" value="@ViewData["section"]" hidden />
                    <div class="form-group">
                        <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br/>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="5"><span></span> Strongly Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q1" value="4"><span></span> Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="3"><span></span> Neutral
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q1" value="2"><span></span> Disagree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="1"><span></span> Strongly Disagree
                        </label>
                    </div>
                    <div class="form-group">
                        <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q2" value="5"><span></span> Strongly Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q2" value="4"><span></span> Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q2" value="3"><span></span> Neutral
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q2" value="2"><span></span> Disagree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="1"><span></span> Strongly Disagree
                        </label>
                    </div>
                    <div class="form-group">
                        <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q3" value="5"><span></span> Strongly Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q3" value="4"><span></span> Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q3" value="3"><span></span> Neutral
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q3" value="2"><span></span> Disagree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q3" value="1"><span></span> Strongly Disagree
                        </label>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material">
                                <textarea class="form-control" id="material-textarea-large" name="comments" rows="8" placeholder="Please add a comment"></textarea>
                                <label for="material-textarea-large">Comments</label>
                            </div>
                        </div>
                    </div>
                    @*<div class="form-group">
                            <div class="form-material floating">
                                <select class="form-control" id="feedbackType" name="feedbackType" size="1">
                                    <option></option>
                                    <option value="daily">Daily</option>
                                    <option value="monthly">Monthly</option>
                                    <option value="semister">Semister</option>
                                </select>
                                <label for="feedbackType">Please Select Feedback type</label>
                            </div>
                        </div>*@
                    <div class="form-group">
                        <div class="col-sm-9">
                            <button class="btn btn-sm btn-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- END Static Labels -->
    </div>
</div>

src/Project01-Team07/Views/Feedbacks/Delete.cshtml
@model Project01_Team07.Models.Feedback

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Feedback</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FeedbackComment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FeedbackComment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FeedbackResponse)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FeedbackResponse)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.crn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.crn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/Project01-Team07/Views/Feedbacks/Failure.cshtml
@{
    ViewData["Title"] = "Feedback Failure";
}
<!-- Page Header -->
<div class="content bg-image overflow-hidden" style="background-image: url('/assets/img/photos/photo3@2x.jpg');">
    <div class="push-50-t push-15">
        <h1 class="h2 text-white animated zoomIn">Failure</h1>
        <h2 class="h5 text-white-op animated zoomIn">Unable to submit the feeback</h2>
    </div>
</div>
<!-- END Page Header -->
<label>Unable to submit the Feedback. Please try it again </label>

src/Project01-Team07/Views/Feedbacks/Month.cshtml
@{
    ViewData["Title"] = "Monthly - Feedback";
}

<h2>Daily - Feedback</h2>

<div class="content content-narrow">
    <!-- Material Design -->
    @*<h2 class="content-heading">Material Design</h2>*@
    <div class="row bg-white">
        <!-- Static Labels -->
        <div class="block">
            <div class="block-header bg-gray-lighter">
                <h3 class="block-title">Feedback Generation</h3>
            </div>
            <div class="block-content">
                <form class="form-horizontal push-10-t" asp-controller="Feedbacks" asp-action="MonthSave" method="post">
                    <input type="text" name="crn" value="@ViewData["section"]" hidden />
                    <div class="form-group">
                        <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br/>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="5"><span></span> Strongly Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q1" value="4"><span></span> Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="3"><span></span> Neutral
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q1" value="2"><span></span> Disagree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="1"><span></span> Strongly Disagree
                        </label>
                    </div>
                    <div class="form-group">
                        <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q2" value="5"><span></span> Strongly Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q2" value="4"><span></span> Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q2" value="3"><span></span> Neutral
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q2" value="2"><span></span> Disagree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q1" value="1"><span></span> Strongly Disagree
                        </label>
                    </div>
                    <div class="form-group">
                        <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q3" value="5"><span></span> Strongly Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q3" value="4"><span></span> Agree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q3" value="3"><span></span> Neutral
                        </label>
                        <label class="css-input css-radio css-radio-primary">
                            <input type="radio" name="q3" value="2"><span></span> Disagree
                        </label>
                        <label class="css-input css-radio css-radio-primary push-10-r">
                            <input type="radio" name="q3" value="1"><span></span> Strongly Disagree
                        </label>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material">
                                <textarea class="form-control" id="material-textarea-large" name="comments" rows="8" placeholder="Please add a comment"></textarea>
                                <label for="material-textarea-large">Comments</label>
                            </div>
                        </div>
                    </div>
                    @*<div class="form-group">
                            <div class="form-material floating">
                                <select class="form-control" id="feedbackType" name="feedbackType" size="1">
                                    <option></option>
                                    <option value="daily">Daily</option>
                                    <option value="monthly">Monthly</option>
                                    <option value="semister">Semister</option>
                                </select>
                                <label for="feedbackType">Please Select Feedback type</label>
                            </div>
                        </div>*@
                    <div class="form-group">
                        <div class="col-sm-9">
                            <button class="btn btn-sm btn-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- END Static Labels -->
    </div>
</div>

src/Project01-Team07/Views/Feedbacks/Semister.cshtml
@{
    ViewData["Title"] = "Semister Feedback";
}

<h2>Daily - Feedback</h2>

<div class="content content-narrow">
    <!-- Material Design -->
    @*<h2 class="content-heading">Material Design</h2>*@
    <div class="row bg-white">
        <!-- Static Labels -->
        <div class="block">
            <div class="block-header bg-gray-lighter">
                <h3 class="block-title">Feedback Generation</h3>
            </div>
            <div class="block-content">
                <form class="form-horizontal push-10-t" asp-controller="Feedbacks" asp-action="SemisterSave" method="post">
                        <div class="form-group">
                            <input type="text" name="crn" value="@ViewData["section"]" hidden/>
                        </div>
                        <div class="form-group">
                            <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q1" value="5"><span></span> Strongly Agree
                            </label>
                            <label class="css-input css-radio css-radio-primary">
                                <input type="radio" name="q1" value="4"><span></span> Agree
                            </label>
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q1" value="3"><span></span> Neutral
                            </label>
                            <label class="css-input css-radio css-radio-primary">
                                <input type="radio" name="q1" value="2"><span></span> Disagree
                            </label>
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q1" value="1"><span></span> Strongly Disagree
                            </label>
                        </div>
                        <div class="form-group">
                            <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q2" value="5"><span></span> Strongly Agree
                            </label>
                            <label class="css-input css-radio css-radio-primary">
                                <input type="radio" name="q2" value="4"><span></span> Agree
                            </label>
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q2" value="3"><span></span> Neutral
                            </label>
                            <label class="css-input css-radio css-radio-primary">
                                <input type="radio" name="q2" value="2"><span></span> Disagree
                            </label>
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q1" value="1"><span></span> Strongly Disagree
                            </label>
                        </div>
                        <div class="form-group">
                            <label>The Instructor requried that students use course concepts to demonstrate understanding </label><br />
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q3" value="5"><span></span> Strongly Agree
                            </label>
                            <label class="css-input css-radio css-radio-primary">
                                <input type="radio" name="q3" value="4"><span></span> Agree
                            </label>
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q3" value="3"><span></span> Neutral
                            </label>
                            <label class="css-input css-radio css-radio-primary">
                                <input type="radio" name="q3" value="2"><span></span> Disagree
                            </label>
                            <label class="css-input css-radio css-radio-primary push-10-r">
                                <input type="radio" name="q3" value="1"><span></span> Strongly Disagree
                            </label>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <div class="form-material">
                                    <textarea class="form-control" id="material-textarea-large" name="comments" rows="8" placeholder="Please add a comment"></textarea>
                                    <label for="material-textarea-large">Comments</label>
                                </div>
                            </div>
                        </div>
                        @*<div class="form-group">
                <div class="form-material floating">
                    <select class="form-control" id="feedbackType" name="feedbackType" size="1">
                        <option></option>
                        <option value="daily">Daily</option>
                        <option value="monthly">Monthly</option>
                        <option value="semister">Semister</option>
                    </select>
                    <label for="feedbackType">Please Select Feedback type</label>
                </div>
            </div>*@
                        <div class="form-group">
                            <div class="col-sm-9">
                                <button class="btn btn-sm btn-primary" type="submit">Submit</button>
                            </div>
                        </div>
</form>
            </div>
        </div>

        <!-- END Static Labels -->
    </div>
</div>